ARG APP_PATH=/opt/outline
FROM 419667429555.dkr.ecr.us-east-1.amazonaws.com/outline:base-3.16 as base

ARG APP_PATH
WORKDIR $APP_PATH

# ---
FROM node:16.14.2-alpine3.15 AS runner

# PostgreSQL
ARG DATABASE_URL 
ARG SECRET_KEY
ARG UTILS_SECRET
ENV DATABASE_URL=$DATABASE_URL
ENV SECRET_KEY=$SECRET_KEY
ENV UTILS_SECRET=$UTILS_SECRET

# S3 Bucket
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY 
ARG AWS_REGION 
ARG AWS_S3_ACCELERATE_URL 
ARG AWS_S3_UPLOAD_BUCKET_URL 
ARG AWS_S3_UPLOAD_BUCKET_NAME
ARG AWS_S3_UPLOAD_MAX_SIZE
ARG AWS_S3_FORCE_PATH_STYLE
ARG AWS_S3_ACL

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_REGION=$AWS_REGION
ENV AWS_S3_ACCELERATE_URL=$AWS_S3_ACCELERATE_URL
ENV AWS_S3_UPLOAD_BUCKET_URL=$AWS_S3_UPLOAD_BUCKET_URL
ENV AWS_S3_UPLOAD_BUCKET_NAME=$AWS_S3_UPLOAD_BUCKET_NAME
ENV AWS_S3_UPLOAD_MAX_SIZE=$AWS_S3_UPLOAD_MAX_SIZE
ENV AWS_S3_FORCE_PATH_STYLE=$AWS_S3_FORCE_PATH_STYLE
ENV AWS_S3_ACL=$AWS_S3_ACL

# SSO Login
ARG SAML_CERT
ARG SAML_SSO_ENDPOINT
ENV SAML_CERT=$SAML_CERT
ENV SAML_SSO_ENDPOINT=$SAML_SSO_ENDPOINT


# Redis Cluster
ARG REDIS_URL
ENV REDIS_URL=$REDIS_URL

# URL
ARG URL
ENV URL=$URL

ARG APP_PATH
WORKDIR $APP_PATH
ENV NODE_ENV production

COPY --from=base $APP_PATH/build ./build
COPY --from=base $APP_PATH/server ./server
COPY --from=base $APP_PATH/public ./public
COPY --from=base $APP_PATH/.sequelizerc ./.sequelizerc
COPY --from=base $APP_PATH/node_modules ./node_modules
COPY --from=base $APP_PATH/package.json ./package.json

RUN addgroup -g 1001 -S nodejs && \
  adduser -S nodejs -u 1001 && \
  chown -R nodejs:nodejs $APP_PATH/build

USER nodejs

EXPOSE 3000
CMD ["yarn", "start"]
