{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "outline.fullname" . }}
data:
{{- with .Values.configmap.configs }}
  {{- toYaml . | nindent 2 -}}
{{- end }}
{{- end }}
