name: Build and push Docker base image

on:
  push:
    paths:
      - ./Dockerfile.base
    branches:
      - master
  workflow_dispatch:

env:
  ALPINE_VERSION: 3.15


jobs:
  build-and-push-docker-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/aws-actions/configure-aws-credentials (Community)
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # https://github.com/aws-actions/amazon-ecr-login (Community)
      - name: 'Login To Amazon ECR'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # In this section, we are Preparing Docker images  and push AWS ECR
      - name: 'Prepare Docker Images and push to Amazon ECR'
        env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: outline
         IMAGE_TAG: base-${{ env.ALPINE_VERSION }}
        run: |
           docker build -f Dockerfile.base --no-cache \
           -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
           docker rmi $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      
      
      
